package com.loan.entity;

public enum Status {

	PENDING,
	APPROVED,
	ACCEPT,
	WAITING_FOR_FINANACE_APPROVAL,
	WAITING_FOR_REVIEW,
	REJECTED,
	DOCUMENTS_UPLOEADED,
	DOCUMENTS_NOT_UPLOADED
}
